import { CleaningPlan } from './types';

export const mockCleaningPlans: CleaningPlan[] = [
    {
        id: 'P001',
        name: 'Standard Room Clean',
        client: 'NH Hotels Nederland',
        location: 'NH Hotel Amsterdam Centrum',
        rooms: ['Kamer 101', 'Kamer 201'],
        duration: 45,
        photos: 4,
        tasks: 12,
        aiValid: true,
        checklistTasks: [
            'Vacuum floor',
            'Mop floor',
            'Clean bathroom',
            'Replace towels',
            'Replace linen',
            'Empty trash',
            'Wipe surfaces',
            'Clean mirrors',
            'Sanitize toilet',
            'Restock amenities',
            'Make bed',
            'Dust furniture',
        ],
        photoRequirements: [
            'Bathroom before',
            'Bathroom after',
            'Bedroom before',
            'Bedroom after',
        ],
        photoRotation: 'Daily rotating selection',
        periodicTasks: [
            { task: 'Clean toilet air vents', frequencyDays: 30, lastCompleted: '2026-07-02', due: true },
            { task: 'Clean skirting boards', frequencyDays: 7, lastCompleted: '2026-07-25', due: false },
        ],
    },
    {
        id: 'P002',
        name: 'Deluxe Room Clean',
        client: 'NH Hotels Nederland',
        location: 'NH Hotel Amsterdam Centrum',
        rooms: ['Kamer 202', 'Suite 701'],
        duration: 60,
        photos: 6,
        tasks: 15,
        aiValid: true,
        checklistTasks: [
            'Vacuum floor',
            'Mop floor',
            'Clean bathroom',
            'Replace towels',
            'Replace linen',
            'Empty trash',
            'Wipe surfaces',
            'Clean mirrors',
            'Sanitize toilet',
            'Restock amenities',
            'Make bed',
            'Dust furniture',
            'Polish fixtures',
            'Clean windows',
            'Arrange toiletries',
        ],
        photoRequirements: [
            'Bathroom before',
            'Bathroom after',
            'Bedroom before',
            'Bedroom after',
            'Living area before',
            'Living area after',
        ],
    },
    {
        id: 'P003',
        name: 'Suite Deep Clean',
        client: 'Kantoorschoonmaak Rotterdam',
        location: 'Hilton Rotterdam',
        rooms: ['Suite 701'],
        duration: 90,
        photos: 8,
        tasks: 12,
        aiValid: false,
        checklistTasks: [
            'Deep vacuum all areas',
            'Steam mop floors',
            'Deep clean bathroom',
            'Replace all linen',
            'Empty all trash bins',
            'Disinfect all surfaces',
            'Clean all mirrors',
            'Deep clean toilet',
            'Restock all amenities',
            'Make bed with turn-down',
            'Dust all furniture',
            'Clean balcony',
        ],
        photoRequirements: [
            'Bathroom before',
            'Bathroom after',
            'Bedroom before',
            'Bedroom after',
            'Living area before',
            'Living area after',
            'Balcony before',
            'Balcony after',
        ],
    },
    {
        id: 'P004',
        name: 'Bathroom Express',
        client: 'Zorg & Schoon Utrecht',
        location: 'Zorg & Schoon - UMC Utrecht',
        rooms: ['Zaal 1A', 'Zaal 2B'],
        duration: 20,
        photos: 2,
        tasks: 8,
        aiValid: true,
        checklistTasks: [
            'Clean toilet',
            'Clean sink',
            'Wipe mirrors',
            'Replace towels',
            'Restock soap',
            'Empty trash',
            'Mop floor',
            'Sanitize surfaces',
        ],
        photoRequirements: ['Bathroom before', 'Bathroom after'],
    },
];

export const mockClients = [
    'NH Hotels Nederland',
    'Kantoorschoonmaak Rotterdam',
    'Zorg & Schoon Utrecht',
    'Facility Services Eindhoven',
    'ProClean Groningen',
];

export const mockLocations = [
    'NH Hotel Amsterdam Centrum',
    'Hilton Rotterdam',
    'Zorg & Schoon - UMC Utrecht',
    'Van der Valk Eindhoven',
    'NH Hotel Groningen',
];
