import { authenticated } from "./auth";
import type { ShiftDraftInput, ShiftApi } from "./shifts";
const json = (value: unknown) => ({ headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) });
export type RosterShift = { shift_id: string; client_id: string; client_name: string; location_id: string; location_name: string; start_time: string; end_time: string; duration_hours: number; status: string; shift_notes?: string; rooms_count?: number };
export async function getDailyRoster(date?: string) { return authenticated<{ banner: { header_title?: string; date_str?: string; full_date?: string; total_scheduled_shifts?: number; total_scheduled_hours?: number }; total_team_members: number; team_members: Array<{ worker_id: string; worker_name: string; profile_photo?: string | null; worker_type?: string; shifts_today_count?: number; shifts_today_label?: string; shifts: RosterShift[] }> }>(`/manager/roster/daily${date ? `?target_date=${encodeURIComponent(date)}` : ""}`, { method: "GET" }); }
export async function getWeeklyRoster(startDate?: string) { return authenticated<{ banner: { header_title?: string; range_str?: string; start_date?: string; end_date?: string; total_scheduled_shifts?: number; total_scheduled_hours?: number }; total_team_members: number; team_members: Array<{ worker_id: string; worker_name: string; profile_photo?: string | null; shifts_this_week_count?: number; shifts_this_week_label?: string; daily_schedule: Array<{ day_name?: string; date_str?: string; full_date: string; status?: string; shift_count?: number; shifts: RosterShift[] }> }> }>(`/manager/roster/weekly${startDate ? `?start_date=${encodeURIComponent(startDate)}` : ""}`, { method: "GET" }); }
export async function getMonthlyRoster(month?: number, year?: number) { const q = new URLSearchParams(); if (month) q.set("month", String(month)); if (year) q.set("year", String(year)); return authenticated<{ banner: { header_title?: string; month_str?: string; month?: number; year?: number; total_scheduled_shifts?: number; total_team_members?: number }; days_in_month: number; team_members: Array<{ worker_id: string; worker_name: string; profile_photo?: string | null; total_month_shifts?: number; total_month_shifts_label?: string; daily_summaries: Array<{ day_number?: number; full_date: string; shift_count?: number; total_hours?: number; shifts: RosterShift[] }> }> }>(`/manager/roster/monthly${q.size ? `?${q}` : ""}`, { method: "GET" }); }
export async function getRosterShift(shiftId: string) { return authenticated<{ shift_id: string; worker_id: string; worker_name: string; worker_profile_photo: string; assignment_label: string; location_id: string; location_name: string; location_address: string; start_time: string; end_time: string; time_range: string; date: string; client_id: string; client_name: string; status: string }>(`/manager/roster/shifts/${encodeURIComponent(shiftId)}`, { method: "GET" }); }
export async function deleteRosterShift(shiftId: string) { return authenticated<string>(`/manager/roster/shifts/${encodeURIComponent(shiftId)}`, { method: "DELETE" }); }
export async function createRosterDraft(input: ShiftDraftInput) { return authenticated<ShiftApi>("/manager/roster/drafts", { method: "POST", ...json(input) }); }
export async function getRosterDrafts(page = 1, limit = 100) { return authenticated<{ total_count: number; drafts: ShiftApi[] }>(`/manager/roster/drafts?page=${page}&limit=${limit}`, { method: "GET" }); }
export async function assignRosterShift(input: { draft_id: string; team_leader_id: string; worker_ids: string[]; worker_assignments: Array<{ worker_id: string; shift_role: string }> }) { return authenticated<ShiftApi>("/manager/roster/shifts/assign", { method: "POST", ...json(input) }); }
export async function getRosterClients(search?: string) { return authenticated<unknown>(`/manager/roster/dropdowns/clients${search ? `?search=${encodeURIComponent(search)}` : ""}`, { method: "GET" }); }
export async function getRosterLocations(clientId?: string, search?: string) { const q = new URLSearchParams({ page: "1", limit: "100" }); if (clientId) q.set("client_id", clientId); if (search) q.set("search", search); return authenticated<{ locations: unknown[] }>(`/manager/roster/dropdowns/locations?${q}`, { method: "GET" }); }
export async function getRosterRooms(locationId?: string, search?: string) { const q = new URLSearchParams({ page: "1", limit: "100" }); if (locationId) q.set("location_id", locationId); if (search) q.set("search", search); return authenticated<{ rooms: unknown[] }>(`/manager/roster/dropdowns/rooms?${q}`, { method: "GET" }); }
export async function getRosterWorkers(input: { workerType?: string; status?: string; search?: string; targetDate?: string } = {}) { const q = new URLSearchParams({ page: "1", limit: "100" }); Object.entries({ worker_type: input.workerType, status_filter: input.status, search: input.search, target_date: input.targetDate }).forEach(([key, value]) => { if (value) q.set(key, value); }); return authenticated<{ workers: unknown[] }>(`/manager/roster/dropdowns/workers?${q}`, { method: "GET" }); }
export async function createRosterShift(input: { client_id: string; location_id: string; date: string; start_time: string; end_time: string; worker_ids: string[]; shift_notes: string; cleaning_plan_id?: string; room_ids: string[] }) { return authenticated<ShiftApi>("/manager/roster/shifts", { method: "POST", ...json(input) }); }
