import { authenticated } from "./auth";
export type Period = "today" | "weekly" | "monthly";
export type AttendanceWorker = { worker_id: string; worker_name: string; profile_picture: string; worker_type: string; hours_worked: string; hours_worked_numeric: number; total_shifts: number; late_days: number };
export type LiveWorker = { worker_id: string; worker_name: string; worker_type: string; profile_photo: string; profile_picture: string; position: string; shift_id: string; shift_name: string; location_id: string; location_name: string; client_id: string; client_name: string; shift_start_time: string; shift_end_time: string; checkin_time: string; checkout_time: string; hours_worked_display: string; hours_worked_numeric: number; progress_percentage: number; status: string };
const query = (values: Record<string, string | number | undefined>) => { const q = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => { if (value !== undefined && value !== "") q.set(key, String(value)); }); return q; };
export async function getLiveStatus(input: { page?: number; limit?: number; date?: string; status?: string; workerType?: string; search?: string } = {}) { return authenticated<{ total_shifts_count: number; ontime_count: number; late_count: number; missing_count: number; page: number; limit: number; has_more: boolean; items: LiveWorker[] }>(`/manager/shift-monitoring/live-status?${query({ page: input.page ?? 1, limit: input.limit ?? 100, date_val: input.date, checkin_status: input.status, worker_type: input.workerType, search: input.search })}`, { method: "GET" }); }
export async function getAttendanceTracking(input: { period?: Period; workerType?: string; search?: string; page?: number; limit?: number } = {}) { return authenticated<{ total_count: number; page: number; limit: number; has_more: boolean; workers: AttendanceWorker[] }>(`/manager/shift-monitoring/attendance-time-tracking?${query({ period: input.period ?? "monthly", worker_type: input.workerType, search: input.search, page: input.page ?? 1, limit: input.limit ?? 100 })}`, { method: "GET" }); }
export async function getLocationStatistics(input: { period?: Period; search?: string; page?: number; limit?: number } = {}) { return authenticated<{ total_count: number; page: number; limit: number; has_more: boolean; locations: Array<{ location_id: string; location_name: string; client_id: string; client_name: string; workers_count: number; hours_worked: string; hours_worked_numeric: number; shifts_count: number }> }>(`/manager/shift-monitoring/location-statistics?${query({ period: input.period ?? "monthly", search: input.search, page: input.page ?? 1, limit: input.limit ?? 100 })}`, { method: "GET" }); }
export async function getLiveWorkerDetails(id: string, period: Period = "today") { return authenticated<{ worker_id: string; worker_name: string; worker_type: string; position: string; shift_id: string; shift_label: string; current_status: string; profile_picture: string; period: Period; hours_worked: string; hours_worked_numeric: number; shifts_count: number; avg_duration: string; avg_duration_numeric: number; shift_details: { check_in: string; check_out: string; duration: string; status: string }; activity_history_available: boolean }>(`/manager/shift-monitoring/live-worker-details/${encodeURIComponent(id)}?period=${period}`, { method: "GET" }); }
export async function getWorkerStats(id: string, period: Period = "monthly") { return authenticated<{ worker_id: string; worker_name: string; profile_picture: string; worker_type: string; period: string; total_hours_worked: string; total_hours_worked_numeric: number; total_shifts_count: number; late_days_count: number; avg_shift_duration: string; shifts: Array<{ shift_id: string; client_name: string; location_name: string; date: string; start_time: string; end_time: string; checkin_time: string; checkout_time: string; duration_hours: number; status: string }> }>(`/manager/shift-monitoring/worker-stats/${encodeURIComponent(id)}?period=${period}`, { method: "GET" }); }
export async function getWorkerAttendanceStats(id: string, period: Period = "monthly") { return authenticated<{ worker_id: string; worker_name: string; worker_type: string; profile_picture: string; hours_worked: string; hours_worked_numeric: number; completed_shifts: number; avg_shift_duration: string; avg_shift_duration_numeric: number; late_checkins: number; weekly_hours_trend: Array<{ week_label: string; hours: number }>; monthly_hours_trend: Array<{ month_label: string; hours: number }> }>(`/manager/shift-monitoring/worker-attendance-stats/${encodeURIComponent(id)}?period=${period}`, { method: "GET" }); }
export async function getWorkerDailyActivity(id: string, month?: string) { return authenticated<{ worker_id: string; worker_name: string; profile_picture: string; worker_type: string; month: string; month_iso: string; total_hours_worked: string; total_hours_worked_numeric: number; attendance_percentage: string; attendance_percentage_numeric: number; late_days: number; absent_days: number; total_shifts: number; daily_activity: Array<{ shift_id: string; date: string; date_iso: string; check_in_time: string; check_out_time: string; total_hours: string; total_hours_numeric: number; status: string }> }>(`/manager/shift-monitoring/worker-daily-activity?${query({ worker_id: id, month })}`, { method: "GET" }); }
