import { authenticated } from "./auth";
export type ShiftRoomInput = { room_id: string; custom_room_name?: string; additional_tasks?: Array<{ name: string }>; additional_photo_requirements?: Array<{ name: string }>; duration?: number; clean_type?: string; tasks?: unknown[]; required_photos?: unknown[] };
export type ShiftDraftInput = { client_id: string; location_id: string; date: string; start_time: string; end_time: string; repeat_shift: string; shift_notes: string; cleaning_plan_id?: string; room_ids: string[]; rooms: ShiftRoomInput[] };
export type ShiftApi = { id: string; draft_id?: string; client_id: string; client_name: string; location_id: string; location_name: string; date: string; start_time: string; end_time: string; repeat_shift?: string; shift_notes: string; cleaning_plan_id: string; rooms: Array<{ room_id: string; room_name: string; status: string }>; total_tasks_count: number; total_photo_required: number; status: string; workers?: Array<{ worker_id: string; name: string; profile_picture: string; worker_type: string; shift_role: string }> };
const json = (value: unknown) => ({ headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) });
export async function createShiftDraft(input: ShiftDraftInput) { return authenticated<ShiftApi>("/manager/shifts/drafts", { method: "POST", ...json(input) }); }
export async function getShiftDrafts(page = 1, limit = 100) { return authenticated<{ total_count: number; page: number; limit: number; has_more: boolean; drafts: ShiftApi[] }>(`/manager/shifts/drafts?page=${page}&limit=${limit}`, { method: "GET" }); }
export async function assignAndPublishShift(input: { draft_id: string; team_leader_id: string; worker_ids: string[]; worker_assignments: Array<{ worker_id: string; shift_role: string }> }) { return authenticated<ShiftApi>("/manager/shifts/assign", { method: "POST", ...json(input) }); }
export async function getShifts(input: { page?: number; limit?: number; clientId?: string; locationId?: string; date?: string; status?: string } = {}) { const q = new URLSearchParams({ page: String(input.page ?? 1), limit: String(input.limit ?? 100) }); if (input.clientId) q.set("client_id", input.clientId); if (input.locationId) q.set("location_id", input.locationId); if (input.date) q.set("date", input.date); if (input.status) q.set("status_filter", input.status); return authenticated<{ total_count: number; page: number; limit: number; has_more: boolean; shifts: ShiftApi[] }>(`/manager/shifts?${q}`, { method: "GET" }); }
export async function getShift(shiftId: string) { return authenticated<ShiftApi>(`/manager/shifts/${encodeURIComponent(shiftId)}`, { method: "GET" }); }
