"use client";
import { useState } from "react";
import { MdLocationOn, MdSearch } from "react-icons/md";
import { CardGridSkeleton } from "@/components/shared/SkeletonLoader";
import { type Period } from "@/services/actions/shiftMonitoring";
import { useGetLocationStatisticsQuery } from "@/redux/api/shiftMonitoringApi";
type Location = { location_id: string; location_name: string; client_name: string; workers_count: number; hours_worked: string; shifts_count: number };
export function LocationStatistics() { const [period, setPeriod] = useState<Period>("monthly"); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  const { data: locRes, isLoading: loading } = useGetLocationStatisticsQuery({ period, search: search.trim() || undefined });
  const items: Location[] = locRes?.locations ?? [];
  return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-2"><div className="flex rounded bg-slate-100 p-1">{(["today", "weekly", "monthly"] as const).map((value) => <button key={value} onClick={() => setPeriod(value)} className={`rounded px-3 py-1.5 text-xs font-semibold ${period === value ? "bg-white text-sky-600 shadow-sm" : "text-slate-500"}`}>{value}</button>)}</div><label className="relative"><MdSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search locations..." className="h-9 rounded border pl-9 pr-3 text-xs" /></label></div>{error && <p className="rounded bg-red-50 p-3 text-xs text-red-700">{error}</p>}{loading ? <CardGridSkeleton cards={8} /> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map((item) => <div key={item.location_id} className="dashboard-card p-5"><div className="mb-5 flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded bg-sky-50 text-sky-600"><MdLocationOn /></span><div><h3 className="font-semibold">{item.location_name}</h3><p className="text-xs text-slate-400">{item.client_name}</p></div></div><div className="grid grid-cols-3 gap-2 text-center"><Stat value={item.workers_count} label="Workers" /><Stat value={item.hours_worked} label="Hours" /><Stat value={item.shifts_count} label="Shifts" /></div></div>)}{items.length === 0 && <p className="col-span-full py-16 text-center text-sm text-slate-500">No locations</p>}</div>}</div>; }
function Stat({ value, label }: { value: string | number; label: string }) { return <div><b className="text-lg text-slate-800">{value}</b><p className="text-[10px] uppercase text-slate-400">{label}</p></div>; }
