"use client";
import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { MdAdd, MdArrowBack, MdDelete, MdDownload, MdEmail, MdUploadFile } from "react-icons/md";
import { AddContactModal } from "@/components/clients/AddContactModal";
import { ClientLocationsPanel } from "@/components/clients/ClientLocationsPanel";
import { DetailSkeleton } from "@/components/shared/SkeletonLoader";
import { addClientContact, emailClientReport, exportClientReport, generateClientReport, getClient, getClientContacts, getClientContract, getClientOverview, getClientReports, removeClientContact, renewClientContract, updateClient, uploadClientContract, type ClientContact, type ClientDetails, type ClientReport, type ClientSummary, type Contract } from "@/services/actions/clients";
type Tab = "Overview" | "Contacts" | "Locations" | "Contract" | "Reports";
export default function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = use(params); const router = useRouter(); const [client, setClient] = useState<ClientDetails | null>(null); const [overview, setOverview] = useState<Record<string, unknown> | null>(null); const [contacts, setContacts] = useState<ClientContact[]>([]); const [contract, setContract] = useState<Contract | null>(null); const [reports, setReports] = useState<ClientReport[]>([]); const [tab, setTab] = useState<Tab>("Overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [contactOpen, setContactOpen] = useState(false); const [editing, setEditing] = useState(false);
  const loadBase = async () => { setLoading(true); const result = await getClient(id); setLoading(false); if (!result.success) return setError(result.error); setClient(result.data); }; useEffect(() => { void loadBase(); }, [id]);
  useEffect(() => { if (tab === "Overview") void getClientOverview(id).then((r) => r.success ? setOverview(r.data as unknown as Record<string, unknown>) : setError(r.error)); if (tab === "Contacts") void getClientContacts(id).then((r) => r.success ? setContacts(r.data.contacts) : setError(r.error)); if (tab === "Contract") void getClientContract(id).then((r) => r.success ? setContract(r.data) : setError(r.error)); if (tab === "Reports") void getClientReports(id).then((r) => r.success ? setReports(r.data.reports) : setError(r.error)); }, [tab, id]);
  if (loading) return <DetailSkeleton blocks={8} />; if (!client) return <p className="rounded bg-red-50 p-4 text-red-700">{error || "Client not found"}</p>;
  return <div className="space-y-5 pb-10"><header className="flex flex-wrap items-center gap-3"><button onClick={() => router.push("/clients")} className="rounded border p-2"><MdArrowBack /></button><div><h1 className="text-xl font-bold">{client.company_name}</h1><p className="text-xs text-slate-500">{client.industry} · {client.status}</p></div><button onClick={() => setEditing((value) => !value)} className="ml-auto rounded bg-sky-500 px-4 py-2 text-xs font-semibold text-white">{editing ? "Cancel edit" : "Edit client"}</button></header>{error && <p className="rounded bg-red-50 p-3 text-xs text-red-700">{error}</p>}<nav className="flex overflow-x-auto border-b">{(["Overview", "Contacts", "Locations", "Contract", "Reports"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-5 py-3 text-xs font-semibold ${tab === item ? "border-sky-500 text-sky-600" : "border-transparent text-slate-400"}`}>{item}</button>)}</nav>
    {editing && <EditClient client={client} onSaved={(value) => { setClient(value); setEditing(false); }} onError={setError} />}
    {!editing && tab === "Overview" && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Object.entries(overview ?? {}).filter(([, value]) => ["string", "number"].includes(typeof value)).map(([key, value]) => <Info key={key} label={key} value={String(value)} />)}</div>}
    {!editing && tab === "Contacts" && <div className="space-y-4"><button onClick={() => setContactOpen(true)} className="flex items-center gap-1 rounded bg-sky-500 px-4 py-2 text-xs font-semibold text-white"><MdAdd />Add contact</button><div className="grid gap-3 md:grid-cols-2">{contacts.map((item) => <div key={item.id} className="dashboard-card p-5"><div className="flex justify-between"><div><b>{item.name}</b><p className="text-xs text-sky-600">{item.role}</p></div><button onClick={async () => { if (!window.confirm("Delete contact?")) return; const result = await removeClientContact(id, item.id); if (!result.success) return setError(result.error); setContacts((current) => current.filter((contact) => contact.id !== item.id)); }} className="text-red-500"><MdDelete /></button></div><p className="mt-3 text-xs text-slate-500">{item.email}<br />{item.phone}</p></div>)}</div>{contactOpen && <AddContactModal onClose={() => setContactOpen(false)} onSave={async (input) => { const result = await addClientContact(id, input); if (!result.success) return setError(result.error); setContacts((current) => [...current, result.data]); setContactOpen(false); }} />}</div>}
    {!editing && tab === "Locations" && <ClientLocationsPanel clientId={id} onError={setError} />}
    {!editing && tab === "Contract" && <ContractPanel clientId={id} contract={contract} setContract={setContract} onError={setError} />}
    {!editing && tab === "Reports" && <ReportsPanel clientId={id} reports={reports} setReports={setReports} clientEmail={client.email} onError={setError} />}
  </div>; }
function EditClient({ client, onSaved, onError }: { client: ClientDetails; onSaved: (value: ClientDetails) => void; onError: (value: string) => void }) { const [saving, setSaving] = useState(false); const [form, setForm] = useState({ company_name: client.company_name, email: client.email, industry: client.industry, phone: client.phone, primary_contact_name: client.primary_contact_name, is_signup: client.is_signup, status: client.status }); return <form onSubmit={async (e) => { e.preventDefault(); setSaving(true); const result = await updateClient(client.id, form); setSaving(false); if (result.success) onSaved(result.data); else onError(result.error); }} className="grid gap-3 rounded border bg-white p-5 md:grid-cols-2">{(["company_name", "email", "industry", "phone", "primary_contact_name"] as const).map((key) => <label key={key} className="text-xs capitalize text-slate-500">{key.replaceAll("_", " ")}<input required value={String(form[key])} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} className="mt-1 h-10 w-full rounded border px-3 text-sm text-slate-800" /></label>)}<label className="text-xs capitalize text-slate-500">Status<select value={form.status} onChange={(e) => setForm((current) => ({ ...current, status: e.target.value }))} className="mt-1 h-10 w-full rounded border px-3 text-sm text-slate-800"><option value="active">Active</option><option value="inactive">Inactive</option><option value="pending">Pending</option></select></label><button disabled={saving} className="rounded bg-sky-500 px-4 py-2 text-sm font-semibold text-white md:col-span-2 disabled:opacity-60">{saving ? "Saving..." : "Save changes"}</button></form>; }
function ContractPanel({ clientId, contract, setContract, onError }: { clientId: string; contract: Contract | null; setContract: (value: Contract) => void; onError: (value: string) => void }) { const [busy, setBusy] = useState(false); return <div className="max-w-xl space-y-4"><div className="dashboard-card space-y-2 p-5"><Info label="Status" value={contract?.status || "—"} /><Info label="Expiry" value={contract?.expiry_date_formatted || "—"} /></div><div className="grid grid-cols-3 gap-2"><label className={`rounded border p-4 text-center text-xs font-semibold text-sky-600 ${busy ? "cursor-not-allowed opacity-60" : "cursor-pointer"}`}><MdUploadFile className="mx-auto text-xl" />{busy ? "Uploading..." : "Upload"}<input type="file" accept="application/pdf" disabled={busy} className="hidden" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); const result = await uploadClientContract(clientId, file); if (!result.success) { setBusy(false); return onError(result.error); } const refreshed = await getClientContract(clientId); setBusy(false); if (refreshed.success) setContract(refreshed.data); else onError(refreshed.error); e.target.value = ""; }} /></label><a href={contract?.pdf_url || undefined} target="_blank" rel="noreferrer" aria-disabled={!contract?.pdf_url} className={`rounded border p-4 text-center text-xs font-semibold text-emerald-600 ${!contract?.pdf_url ? "pointer-events-none opacity-50" : ""}`}><MdDownload className="mx-auto text-xl" />View</a><button disabled={busy} onClick={async () => { const date = window.prompt("New expiry date (YYYY-MM-DD)"); if (!date) return; setBusy(true); const result = await renewClientContract(clientId, date); setBusy(false); if (result.success) setContract(result.data); else onError(result.error); }} className="rounded border p-4 text-xs font-semibold text-amber-600 disabled:opacity-60">Renew</button></div></div>; }
function ReportsPanel({ clientId, reports, setReports, clientEmail, onError }: { clientId: string; reports: ClientReport[]; setReports: (value: ClientReport[]) => void; clientEmail: string; onError: (value: string) => void }) { return <div className="space-y-4"><button onClick={async () => { const result = await generateClientReport(clientId); if (result.success) setReports([result.data, ...reports]); else onError(result.error); }} className="rounded bg-sky-500 px-4 py-2 text-xs font-semibold text-white">Generate report</button><div className="divide-y rounded border bg-white">{reports.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 p-4"><div className="flex-1"><b className="text-sm">{item.title}</b><p className="text-xs text-slate-500">{item.date_formatted} · {item.status}</p></div><button onClick={async () => { const result = await exportClientReport(clientId, item.id); if (!result.success) return onError(result.error); window.open(result.data, "_blank"); }} className="rounded border p-2 text-sky-600"><MdDownload /></button><button onClick={async () => { const email = window.prompt("Email", clientEmail); if (!email) return; const result = await emailClientReport(clientId, item.id, email); if (!result.success) onError(result.error); }} className="rounded border p-2 text-amber-600"><MdEmail /></button></div>)}</div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded bg-slate-50 p-4"><p className="text-[10px] uppercase text-slate-400">{label.replaceAll("_", " ")}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
