import { PhotoReview } from "./types";


export const mockReviews: PhotoReview[] = [
    {
        id: "RV-001",
        cleaner: { name: "Lisa Visser", initials: "LV", avatarColor: "#3B82F6" },
        client: "NH Hotels Nederland",
        location: "NH Hotel Amsterdam Centrum",
        room: "Kamer 201",
        dateSubmitted: "09 Jun 2026, 09:15",
        aiScore: 91,
        aiConfidence: 72,
        status: "Pending Review",
        shiftId: "S-1041",
        submittedBy: "Lisa Visser",
        aiAnalysis: {
            overallScore: 91,
            qualityScore: 92,
            coverageScore: 89,
            imageQualityScore: 94,
            brightnessScore: 88,
            suggestion: "Approve",
            notes: ["Floor appears clean.", "Coverage acceptable.", "Mirror visibility detected."],
        },
        beforeImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
        afterImage: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&h=400&fit=crop",
    },
    {
        id: "RV-002",
        cleaner: { name: "Emma Smit", initials: "ES", avatarColor: "#10B981" },
        client: "Kantoorschoonmaak Rotterdam",
        location: "Hilton Rotterdam",
        room: "Kamer 701",
        dateSubmitted: "09 Jun 2026, 08:42",
        aiScore: 88,
        aiConfidence: 85,
        status: "Approved",
        aiAnalysis: {
            overallScore: 88,
            qualityScore: 90,
            coverageScore: 86,
            imageQualityScore: 91,
            brightnessScore: 84,
            suggestion: "Approve",
            notes: ["Room thoroughly cleaned.", "Beds made correctly.", "Bathroom sanitized."],
        },
    },
    {
        id: "RV-003",
        cleaner: { name: "Noah Bos", initials: "NB", avatarColor: "#6366F1" },
        client: "NH Hotels Nederland",
        location: "NH Hotel Groningen",
        room: "Kamer 105",
        dateSubmitted: "09 Jun 2026, 09:15",
        aiScore: 43,
        aiConfidence: 38,
        status: "Rejected",
        aiAnalysis: {
            overallScore: 43,
            qualityScore: 40,
            coverageScore: 45,
            imageQualityScore: 50,
            brightnessScore: 38,
            suggestion: "Reject",
            notes: ["Dust visible on surfaces.", "Incomplete coverage detected.", "Low image brightness."],
        },
    },
    {
        id: "RV-004",
        cleaner: { name: "Sophie de Boer", initials: "SB", avatarColor: "#F59E0B" },
        client: "Facility Services Eindhoven",
        location: "Van der Valk Eindhoven",
        room: "Suite 1204",
        dateSubmitted: "09 Jun 2026, 10:02",
        aiScore: 76,
        aiConfidence: 61,
        status: "Pending Review",
        aiAnalysis: {
            overallScore: 76,
            qualityScore: 78,
            coverageScore: 74,
            imageQualityScore: 80,
            brightnessScore: 72,
            suggestion: "Review",
            notes: ["Some areas may need re-cleaning.", "Coverage partially acceptable.", "Image quality moderate."],
        },
    },
    {
        id: "RV-005",
        cleaner: { name: "Anna Mulder", initials: "AM", avatarColor: "#EC4899" },
        client: "Zorg & Schoon Utrecht",
        location: "Zorg & Schoon – UMC Utrecht",
        room: "Zaal 1A",
        dateSubmitted: "09 Jun 2026, 06:45",
        aiScore: 95,
        aiConfidence: 92,
        status: "Approved",
        aiAnalysis: {
            overallScore: 95,
            qualityScore: 96,
            coverageScore: 94,
            imageQualityScore: 97,
            brightnessScore: 93,
            suggestion: "Approve",
            notes: ["Excellent cleanliness.", "Full coverage confirmed.", "High image quality."],
        },
    },
    {
        id: "RV-006",
        cleaner: { name: "Milan Dekker", initials: "MD", avatarColor: "#14B8A6" },
        client: "NH Hotels Nederland",
        location: "NH Hotel Amsterdam Centrum",
        room: "Kamer 303",
        dateSubmitted: "09 Jun 2026, 11:30",
        aiScore: 67,
        aiConfidence: 54,
        status: "Pending Review",
        aiAnalysis: {
            overallScore: 67,
            qualityScore: 65,
            coverageScore: 70,
            imageQualityScore: 68,
            brightnessScore: 65,
            suggestion: "Review",
            notes: ["Partial cleaning detected.", "Coverage needs improvement.", "Moderate image quality."],
        },
    },
];